version: '3.8'

services:
  frontend:
    build:
      context: ./apollon
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    volumes:
      - ./apollon:/app
      - /app/node_modules
    command: yarn start

  backend:
    build:
      context: ./besser
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./besser:/app 