services:
  frontend:
    build:
      context: ./apollon
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - HUSKY=0
      - DISABLE_HUSKY=1
      - CI=true
    volumes:
      - ./apollon:/app
      - /app/node_modules
    command: yarn start

  backend:
    build:
      context: ./besser
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./besser:/app
    working_dir: /app/besser/utilities/besser_backend
    command: python main.py